modLoader="javafml"
loaderVersion="[44,)"
license="MIT"

[[mods]]
modId="spruceui"
version="${version}"
displayName="ObsidianUI"
displayURL="https://github.com/ThinkingStudios/SpruceUI-Forged"
logoFile= "icon.png"
credits="LambdAurora"
authors="TexTrue, TexTrueStudio"
description='''
Just a GUI library.
'''

[[dependencies.spruceui]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spruceui]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spruceui]]
modId = "architectury"
mandatory = true
versionRange = "[7,)"
ordering = "NONE"
side = "CLIENT"
