modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "obsidianui"
version = "${version}"
displayName = "ObsidianUI"
displayURL = "https://github.com/ThinkingStudios/SpruceUI-Forged"
credits="LambdAurora"
authors="TexTrue, TexTrueStudio"
description='''
SpruceUI unofficial forge port.

Just a GUI library.
'''
logoFile = "icon.png"

[[mixins]]
config = "spruceui.mixins.json"

[[dependencies.obsidianui]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.obsidianui]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.3,)"
ordering = "NONE"
side = "BOTH"