modLoader="javafml"
loaderVersion="[45,)"
license="MIT"

[[mods]]
modId="spruceui"
version="${version}"
displayName="ObsidianUI"
displayURL="https://github.com/ThinkingStudios/SpruceUI-Forged"
logoFile= "icon.png"
credits="LambdAurora"
authors="TexTrue, TexTrueStudio"
description='''
SpruceUI unofficial forge port.

Just a GUI library.
'''

[[dependencies.spruceui]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spruceui]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spruceui]]
modId = "architectury"
mandatory = true
versionRange = "[8,)"
ordering = "NONE"
side = "CLIENT"