modLoader="javafml"
loaderVersion="[38,)"
license="MIT"

[[mods]]
modId="spruceui"
version="${version}"
displayName="ObsidianUI"
displayURL="https://github.com/ThinkingStudios/SpruceUI-Forged"
logoFile= "icon.png"
credits="LambdAurora"
authors="TexTrue, TexTrueStudio"
description='''


Just a GUI library.
'''

[[dependencies.spruceui]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spruceui]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.18.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.spruceui]]
modId = "architectury"
mandatory = true
versionRange = "[3,)"
ordering = "NONE"
side = "CLIENT"