modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "obsidianui"
version = "${version}"
displayName = "ObsidianUI for NeoForge"
displayURL = "https://github.com/ThinkingStudios/SpruceUI-Forged"
credits="LambdAurora"
authors="TexTrue, TexTrueStudio"
description='''
SpruceUI unofficial forge port.

Just a GUI library.
'''
logoFile = "icon.png"

[[mixins]]
config = "spruceui.neoforge.mixins.json"

[[dependencies.obsidianui]]
modId = "neoforge"
mandatory = true
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.obsidianui]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"