modLoader="javafml"
loaderVersion="[46,)"
license="MIT"

[[mods]]
modId="obsidianui_test"
version="${version}"
displayName="ObsidianUI-Test"
displayURL="https://github.com/ThinkingStudios/SpruceUI-Forged"
logoFile= "icon.png"
credits="LambdAurora"
authors="TexTrue, TexTrueStudio"
description='''

'''

[[dependencies.obsidianui_test]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.obsidianui_test]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"